### PR TITLE
gha: simplify env matrix

### PR DESCRIPTION
**Pull request by dtrifiro**
This simplifies the matrix logic a little bit.

### CODE REVIEW

**Comment by joerunde** [comment]
@dtrifiro does this work because there's only one version of python installed for each matrix entry?

**Comment by dtrifiro** [comment]
I updated the actions so that `proto3` and `core` tests also run as part of the 3.8 job. I'd have preferred to have them run as a separate matrix entry, but I guess this will do for now.

**Comment by dtrifiro** [comment]
Fair enough. I'll try and offload `proto3` and `core` so separate matrix entries.

**Comment by dtrifiro** [comment]
Sorry, no time to get back to this.

**Pull request closed without merging**
