### PR TITLE
Fix bug when fetching model info of partially loaded model

### PR DESCRIPTION
**Pull request by HonakerM**
**What this PR does / why we need it**:
This PR fixes a minor bug where the model_info endpoint would try to read info from a model that was still being loaded. 

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by HonakerM** [comment]
@gabe-l-hart this is a NIT pr but would be nice to have soonish ™️

**Review by gabe-l-hart — CHANGES_REQUESTED** [review]
I think the issue here is a little bit more nuanced than this. The real issue is the line directly below here that calls `model_instance = loaded_model.model()` which blocks on loading. I think rather than just skipping non-loaded models, we should append a `ModelInfo` with some of the fields empty.

(Also tests are all failing, so we'll need to get those working before merging)

**Comment by HonakerM** [comment]
> (Also tests are all failing, so we'll need to get those working before merging)

I misspelled a variable name 😅 

> I think rather than just skipping non-loaded models, we should append a ModelInfo with some of the fields empty.

I'm not sure I agree with this. The `ModelInfo` gets the majority of its info from the module instance and class so we'd only be able to fill in the name of the remote model

**Comment by gabe-l-hart** [comment]
>I'm not sure I agree with this. The ModelInfo gets the majority of its info from the module instance and class so we'd only be able to fill in the name of the remote model

True, but this "just the model name plus non-loaded indicator" is very valuable for non-remote cases where a client needs to check and see if a model has been registered with the system, even if it's not done loading yet.

**Comment by HonakerM** [comment]
@gabe-l-hart sounds good! I just added the response and updated the remote finder to ignore them

**Review by gabe-l-hart — APPROVED** [review]
Looks good!

**Comment by gabe-l-hart** [comment]
Looks like tests are failing

**Comment by HonakerM** [comment]
Rats! I thought I fixed those, just pushed a new commit 🤞

**Review by gabe-l-hart — APPROVED** [review]

**Pull request merged**
